version: '3.7'
# Remember that the network MUST exist in the docker host/swarm
networks:
  backbone:
    external:
      name: backbone
services:
# TODO Add CPU, Memory, Restart and Privilege limits to all containers
  nginx-static:
    image: nginx:latest
    read_only: true
    tmpfs:
      - /var/cache
      - /run
      # Mount an empty docker-entrypoint.d to override the existing scripts in the nginx image
      - /docker-entrypoint.d/
    expose:
      - "80"
    networks:
      - backbone
    volumes:
      - nginx-static-data:/usr/share/nginx:ro
      - nginx-logs:/var/log/nginx
      - ./nginx-static/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs4.papertrailapp.com:36048"
        tag: "{{.Name}}/{{.ID}}"
# TODO secure the django container
  djangosandbox:
    image: etcheverryroberto/djangosandbox:latest
    expose:
      - "8000"
    networks:
      - backbone
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs4.papertrailapp.com:36048"
        tag: "{{.Name}}/{{.ID}}"
# acme.sh will work as a daemon
# on first install of the app, obtain the certs:
# docker exec acme.sh acme.sh --issue -d test.infrastructure-altrium.mywire.org \
# --dns dns_dynu --ocsp-must-staple --keylength 4096
# Then deploy to the shared volume:
# docker exec acme.sh acme.sh --install-cert -d test.infrastructure-altrium.mywire.org \
#--cert-file /etc/nginx/ssl/test.infrastructure-altrium.mywire.org.cer \
#--key-file /etc/nginx/ssl/test.infrastructure-altrium.mywire.org.key \
#--ca-file /etc/nginx/ssl/ca.cer \
#--fullchain-file /etc/nginx/ssl/fullchain.cer \
#--reloadcmd "touch /etc/nginx/ssl/renewed"
# TODO somehow automate either in acme.sh or in the nginx container so the renewed file triggers a reload
  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    command: daemon
    volumes:
      - nginx-certs:/etc/nginx/ssl
    env_file:
      - ./acme.sh.env
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs4.papertrailapp.com:36048"
        tag: "{{.Name}}/{{.ID}}"
  nginx-ssl-load-balancer:
    depends_on:
      - nginx-static
      - djangosandbox
    image: nginx:latest
    read_only: true
    tmpfs:
      - /var/cache
      - /run
      # Mount an empty docker-entrypoint.d to override the existing scripts in the nginx image
      - /docker-entrypoint.d/
    ports:
      - "80:8080"
      - "443:4443"
    networks:
      - backbone
    logging:
      driver: syslog
      options:
        syslog-address: "udp://logs4.papertrailapp.com:36048"
        tag: "{{.Name}}/{{.ID}}"
    volumes:
      - nginx-logs:/var/log/nginx
      - nginx-certs:/etc/nginx/ssl
      - ./nginx-ssl-load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  nginx-logs:
    driver: local
  nginx-certs:
    driver: local
  nginx-static-data:
    driver: local