# Skeleton docker compose file for the dockerized Django Sandbox
version: '3.7'
services:
# TODO I am thinking of making all nginx instances share /var/log and use a name+log.log format
# TODO create an nginx image with the static content
  static:
    image: etcheverryroberto/nginx-static:latest
    ports:
      - "80:80"
    volumes:
      # TODO check how to send these volumes and make them available to all containers and nodes
      - ./static:/usr/share/nginx/static
      - ./var/log/nginx/:/var/log/nginx/
      - ./etc/nginx/:/etc/nginx/
# This is the only container ready
  django:
    image: etcheverryroberto/djangosandbox:latest
    ports:
      - "8000:8000"
# TODO configure certbot to obtain base and wildcard certs for dynu using DNS-01 challenge
  certbot:
    image: certbot/certbot
    # --must-staple --rsa-key-size 4096
# TODO with the above cert generated, configure nginx to serve static and dynamic content
  ssl-load-balancer:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # TODO check how to send these volumes and make them available to all containers and nodes
      - ./var/log/nginx/:/var/log/nginx/
      - ./etc/nginx/:/etc/nginx/